### ISSUE TITLE
run from small cells too

### ISSUE THREAD

**Issue by Cybertrinn** [caiosm1005/Agar.io-bot-explosive#4]
i've noticed that sometimes when you're up in a virus some smaller guys that saw you doing it will try to throw themselves onto you... and then you'll be splitted so, a solution for that is to run from smaller cells too.

**Comment by caiosm1005** [comment]
This happens a lot - some players even suicide just to pop the bot.

I think the fix for #3 might solve this issue, too: I'll modify the bot so that it won't seek viruses with food/small cells nearby.

When a small cell comes close, the bot loses interest on disguising the current virus and flees away.

**Comment by caiosm1005** [comment]
@Cybertrinn Could you please test 73291e40717c6fc43a5c7572d6cc85c7c49b9dba?

I tested it for a while but couldn't find smaller suicider cells this time.

In theory, it works. Maybe [this line](https://github.com/caiosm1005/Agar.io-bot-explosive/blob/master/bot.user.js#L77) needs tweaking.
